import { Metadata } from "next"


// Object name should be metadata
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Default title",
    template: "%s | Template"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "aquamarine", padding: "10px"}}>Header</header>
        {children}
        <footer style={{backgroundColor: "bisque", padding: "10px"}}>Footer</footer>
      </body>
    </html>
  )
}
